import { Threat, wusspurrp, cult, slairva, kvrma, prince, varco, mexxed, dac, kevvon, joe, octo, trry } from "../assets";

export const experiences = [
    {
        title: "Varco",
        company_name: "Producer & GFX Designer",
        icon: varco,
        iconBg: "darkblue",
        date: "Capitan",
        yt: 'https://www.youtube.com/@prodvarco9999',
        ig: 'https://www.instagram.com/v4rco/',
        sc: 'https://soundcloud.com/killnightfall',
    },
    {
        title: "Threat",
        company_name: "Producer & Web Dev",
        icon: Threat,
        iconBg: "darkblue",
        date: "Parot",
        yt: 'https://www.youtube.com/watch?v=c0Mwrybb3aM',
        ig: 'https://www.instagram.com/dasathreat/',
        sc: 'https://soundcloud.com/prod-threat',
    },
    {
        title: "Cult",
        company_name: "Producer & GFX Designer",
        icon: cult,
        iconBg: "darkblue",
        date: "Pirate",
        yt: 'https://www.youtube.com/channel/UCrF9kd4syoDCNCPKbRjLbSw',
        ig: 'https://www.instagram.com/cultpxs/',
        sc: 'https://soundcloud.com/cultpxs',
    },
    {
        title: "Wusspurrp",
        company_name: "Producer",
        icon: wusspurrp,
        iconBg: "darkblue",
        date: "Pirate",
        yt: 'https://www.youtube.com/channel/UCfFjAb0FaZuVY6p4fSc29Aw',
        ig: 'https://www.instagram.com/wusspurrp/',
        sc: 'https://soundcloud.com/foguzb3ghkvo'
    },
    {
        title: "K3vv0n",
        company_name: "Producer, GFX Designer & Artist",
        icon: kevvon,
        iconBg: "black",
        date: "Deckhand",
        yt: 'https://www.youtube.com/channel/UCUNo0J3P-VslRyqN5IkmhDQ',
        ig: 'https://www.instagram.com/k3vv0n/',
        sc: 'https://on.soundcloud.com/QpnMMFf5JuXdmzeEA',
    },
    {
        title: "Slairva",
        company_name: "Producer",
        icon: slairva,
        iconBg: "darkblue",
        date: "Pirate",
        yt: 'https://youtube.com/@slairva',
        ig: 'https://instagram.com/slairva?igshid=MzRlODBiNWFlZA==',
        sc: 'https://on.soundcloud.com/CjLT1Qs87SYmxCoM6',
    },
    {
        title: "Joe",
        company_name: "Producer & Artist",
        icon: joe,
        iconBg: "darkblue",
        date: "Slave",
        yt: 'https://www.youtube.com/channel/UCUNo0J3P-VslRyqN5IkmhDQ',
        ig: 'https://www.instagram.com/prod1joe/',
        sc: 'https://soundcloud.com/xoexoexoe',
    },
    {
        title: "Runnitupterry",
        company_name: "Producer, GFX Designer & Artist",
        icon: trry,
        iconBg: "darkblue",
        date: "Deckhand",
        yt: 'https://www.youtube.com/channel/UCn9SMZltuVfpeAjStj8omyw',
        ig: 'https://www.instagram.com/runitupterry_/',
        sc: 'https://on.soundcloud.com/QpnMMFf5JuXdmzeEA',
    },
    {
        title: "Skxnnyprince",
        company_name: "Producer",
        icon: prince,
        iconBg: "darkblue",
        date: "Pirate",
        yt: 'https://www.youtube.com/@ihateanxiety666/',
        ig: 'https://www.instagram.com/skxnnyprince/',
        sc: 'https://soundcloud.com/skinnyprince',
    },
    {
        title: "Octodog",
        company_name: "Producer",
        icon: octo,
        iconBg: "darkblue",
        date: "Deckhand",
        yt: 'https://www.youtube.com/channel/UCQzQ54KdZp0qsOa7xA34f5g',
        ig: 'https://www.instagram.com/octodog_/',
        sc: 'https://soundcloud.com/prod-octo',
    },
    {
        title: "7kvrma",
        company_name: "Producer",
        icon: kvrma,
        iconBg: "darkblue",
        date: "Pirate",
        yt: 'https://www.youtube.com/channel/UCUNo0J3P-VslRyqN5IkmhDQ',
        ig: 'https://www.instagram.com/7kvrma/',
        sc: 'https://soundcloud.com/user-80155166-926249479',
    },
    {
        title: "pr0d.dac",
        company_name: "Producer",
        icon: dac,
        iconBg: "darkblue",
        date: "Pirate",
        yt: 'https://www.youtube.com/channel/UCWcRtMf1f6Ki5AKEiXT8Whg',
        ig: 'https://www.instagram.com/pr0.dac/',
        sc: 'https://soundcloud.com/user-194654885',
    },
    {
        title: "Mexxed",
        company_name: "Producer & Artist",
        icon: mexxed,
        iconBg: "darkblue",
        date: "Slave",
        yt: 'https://www.youtube.com/channel/UCUNo0J3P-VslRyqN5IkmhDQ',
        ig: 'https://www.instagram.com/meexxd/',
        sc: 'https://soundcloud.com/user-171423819',
    },
];